Pipfile
Pipfile.lock
build.sh
config/settings.py

settings changes for depoloyment to render

---

build.sh

changed build.sh to poetry

---

Pipfile
Pipfile.lock
Procfile
build.sh
config/settings.py

updates to settings, procfile added, env changes

---

Pipfile
Pipfile.lock
config/settings.py

changes for environ and static

---

Pipfile
Pipfile.lock
config/settings.py
config/urls.py
core/urls.py

Added rest framework and confirmed it is working.

added rest framework

---

Pipfile
Pipfile.lock
config/settings.py

installed cors headers

---

Pipfile
Pipfile.lock
config/settings.py
config/urls.py

setup djoser

---

core/serializers.py
core/urls.py
core/views.py

Added the view to test the root api.

added the root api and a view to test

---

core/serializers.py
core/urls.py
core/views.py

4 endpoints for easy, med, hard, bonus chores

---

core/models.py
core/serializers.py
core/urls.py
core/views.py

total points endpoint

---

core/models.py
core/serializers.py
core/urls.py
core/views.py

List for all current users with their points total

Global list

---

backend/core/views.py

added filter to list of chore trackers to only show uncompleted chores

updated list of chore trackers

---

README.md

added friends leaderboard endpoint to the readme

---

cleansweep/src/Components/Pages/Chores/index.js

feat: add button UI change

---

cleansweep/src/Components/Pages/Chores/index.js
cleansweep/src/Components/Pages/MyChores/index.js
cleansweep/src/Endpoints.js
cleansweep/src/hooks/useCart.js

title, still working complete button

feat: add chores routing to my chores and complete and delete button

---

cleansweep/src/Components/LeaderBoardList.js
cleansweep/src/Components/LeaderBoardNumbers.js
cleansweep/src/Components/Pages/LeaderBoards/index.js

Added to files to split off the leaderboard position numbers from the numbers list group.

fixed leaderboard position numbers

---

cleansweep/src/Components/Pages/MyChores/index.js

chores due date shows weekday, and day of month.

updated date output for chores due date

---

cleansweep/src/Components/Pages/Chores/index.js
cleansweep/src/Components/Pages/Login/index.js

fix button to work

---

cleansweep/src/App.css
cleansweep/src/Components/LeaderBoardList.js
cleansweep/src/Components/Pages/Chores/index.js
cleansweep/src/Components/Pages/LeaderBoards/index.js
cleansweep/src/Components/Pages/MyChores/index.js

updates to leaderboard styling, headers, and timezone

Leader style

---

cleansweep/package-lock.json
cleansweep/package.json
cleansweep/src/Components/Pages/MyChores/index.js

Added clean supplies confetti when the chore complete button is clicked.

added confetti to the chore complete button

---

cleansweep/src/Components/Pages/MyChores/index.js

updated time check for front end late chores

Time zones

---

cleansweep/src/Components/Page.js
cleansweep/src/Components/Pages/MyChores/index.js

fix: fix numbers not updating
